---
title: "training_load"
author: "Daniel Fuller"
date: "29/03/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(lubridate)
```

## Simple Training Load Metrics 

Got Garmin activity data and quick analysis of training time 

```{r}
data <- read.csv("Activities_to_2022_03_29.csv")
tibble(data)
```

## General date formatting

```{r}
data$Date <- ymd_hms(data$Date)

data$week <- week(data$Date)
data$year <- year(data$Date)

data$activity_time <- hms(data$Time)
data$activity_time <- as.duration(data$activity_time)
```

## Recoding activity types

```{r}
table(data$Activity.Type)

data <- data %>%
	mutate(activity_type = case_when(
		Activity.Type == "Cardio" ~ "Cardio",
		Activity.Type == "Cross Country Classic Skiing" ~ "XC Skiing",
		Activity.Type == "Cycling" ~ "Cycling",
		Activity.Type == "Hiking" ~ "Cardio",
		Activity.Type == "Indoor Cycling" ~ "Cycling",
		Activity.Type == "Indoor Running" ~ "Running",
		Activity.Type == "Multisport" ~ "Brick",
		Activity.Type == "Open Water Swimming" ~ "Swimming",
		Activity.Type == "Other" ~ "Cardio",
		Activity.Type == "Pool Swimming" ~ "Swimming",
		Activity.Type == "Running" ~ "Running",
		Activity.Type == "Strength Training" ~ "Cardio",
		Activity.Type == "Treadmill Running" ~ "Running",
		Activity.Type == "Virtual Cycling" ~ "Cycling",
		Activity.Type == "Whitewater Kayaking/Rafting" ~ "Cardio",
		Activity.Type == "Yoga" ~ "Cardio",
		TRUE ~ "NOT STATED"
	))

table(data$activity_type)
```

## Grouping by week

```{r}
data_week <- data %>%
              group_by(year, week, activity_type) %>%
              summarize(
                activity_time = sum(activity_time)
              )

data_week$activity_time_m <- data_week$activity_time/60

data_week <- data_week %>% 
              unite("year_week", year:week, remove = FALSE)
```

## Plot by week

```{r}
time_date <- ggplot(data_week, aes(x = week, y = activity_time_m)) + 
                      geom_point() + 
                      geom_smooth(method = "lm") +
                      facet_wrap(~ year)
plot(time_date)
```

## Plot by week by activity type

```{r}
time_date_type <- ggplot(data_week, aes(x = week, y = activity_time_m, colour = activity_type)) + 
                      geom_point() + 
                      #geom_smooth(method = "lm") +
                      facet_wrap(~ year)
plot(time_date_type)
```




